apiVersion: v1
kind: Service
metadata:
  name: argo-postgre-svc
spec:
  selector:
    app: argo-postgre13
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: argo-nodejs-svc
spec:
  selector:
    app: argo-nodejs
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: argo-njnginx-svc
spec:
  selector:
    app: argo-njnginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80